project_id = "hkhssvlinxvoxrosdzfu"

[functions.ai-recommend]
verify_jwt = false

[functions.fetch-cuelinks]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.kriya-chat]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.earnkaro-convert]
verify_jwt = false

[functions.scrape-product]
verify_jwt = false

[functions.ai-content-generate]
verify_jwt = false

[functions.send-to-sheet]
verify_jwt = false

[functions.ai-product-enhance]
verify_jwt = false
