import { motion } from "framer-motion";
import { ArrowLeftRight, ShieldCheck, Zap, Lock } from "lucide-react";

const reasons = [
  {
    icon: ArrowLeftRight,
    title: "Compare Offers",
    desc: "Side-by-side comparison of credit cards, loans, and insurance from multiple banks.",
  },
  {
    icon: ShieldCheck,
    title: "Trusted Partners",
    desc: "All offers come from verified banking partners including HDFC, ICICI, Axis, and SBI.",
  },
  {
    icon: Zap,
    title: "AI-Powered Deals",
    desc: "Smart descriptions and recommendations generated by AI to help you decide faster.",
  },
  {
    icon: Lock,
    title: "Secure Applications",
    desc: "Your data is protected. We redirect you safely to official bank application pages.",
  },
];

const WhyChooseUs = () => {
  return (
    <section className="py-24 bg-secondary/50">
      <div className="container mx-auto px-4 md:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-heading font-bold mb-4 text-foreground">
            Why Choose <span className="text-gradient">Kriyapay</span>
          </h2>
          <p className="text-muted-foreground max-w-xl mx-auto">
            We make financial decisions simple, transparent, and trustworthy.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {reasons.map((r, i) => (
            <motion.div
              key={r.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="text-center p-6 rounded-2xl border border-border bg-card shadow-card card-hover"
            >
              <div className="w-14 h-14 rounded-2xl bg-primary/8 flex items-center justify-center mx-auto mb-4">
                <r.icon className="w-7 h-7 text-primary" />
              </div>
              <h3 className="font-heading font-semibold text-foreground mb-2">{r.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{r.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default WhyChooseUs;
